-- Flyway Migration: V2.4.1.1
-- Purpose: Create DEVICE_TOKEN table for long-lived desktop client logins.
-- Context: Only a SHA-256 hash of each secret is stored. Tokens go with their user.

CREATE SEQUENCE DEVICE_TOKEN_SEQ INCREMENT BY 50;

CREATE TABLE DEVICE_TOKEN
(
    ID           BIGINT                   NOT NULL PRIMARY KEY,
    USER_ID      BIGINT                   NOT NULL,
    NAME         CHARACTER VARYING(100)   NOT NULL,
    TOKEN_HASH   CHARACTER VARYING(64)    NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_USED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_DEVICE_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_DEVICE_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS ON DELETE CASCADE
);

CREATE INDEX IDX_DEVICE_TOKEN_USER ON DEVICE_TOKEN (USER_ID);
